name: Deploy Website to EC2

on:
  push:
    branches:
      - main  # Set this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: arlingeorge/finantial-website:${{ github.sha }}

    - name: Deploy website on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          docker pull arlingeorge/finantial-website:${{ github.sha }}
          docker stop finantial-website || true
          docker rm finantial-website || true
          docker run -d --name finantial-website -p 80:80 arlingeorge/finantial-website:${{ github.sha }}
